"""Add category column to todo table

Revision ID: 09b65c0f4647
Revises: 
Create Date: 2024-09-06 14:58:12.914358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b65c0f4647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('WORK', 'PERSONAL', 'SHOPPING', 'HEALTH', 'OTHER', name='categoryenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
